spring:
  profiles: redis
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    #host: 127.0.0.1
    host: 134.175.153.50
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: root
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）200
        max-active: 8
        # 连接池中的最大空闲连接 20
        max-idle: -1
        # 连接池中的最小空闲连接 0
        min-idle: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
    # 连接超时时间（毫秒）默认是2000ms
    timeout: 2000ms
