spring:
  profiles:
    include: redis
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/oauth2?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false
      username: root
      password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8761}/eureka/
  instance:
    prefer-ip-address: true
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: hystrix.stream
feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true
ribbon:
  ConnectTimeout: 6000
  ReadTimeout: 6000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
hystrix:
  command:
    default:
      execution:
        timeout:
        isolation:
          thread:
            timeoutInMilliseconds: 15000
security:
  oauth2:
    resource:
      jwt:
        key-uri: http://127.0.0.1:7777/sc-auth-server/oauth/token_key	#如果使用JWT，可以获取公钥用于 token 的验签
    client:
      access-token-uri: http://127.0.0.1:7777/sc-auth-server/oauth/token	#令牌端点
      user-authorization-uri: http://127.0.0.1:7777/sc-auth-server/oauth/authorize	#授权端点
      client-id: client_2
      client-secret: 123456
      grant-type: password
      scope: server