spring:
  rabbitmq:
    host: 134.175.153.50
    port: 5672
    virtual-host: testhost
    username: admin
    password: admin
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8761}/eureka/
      #defaultZone: http://${eureka.host:134.175.153.50}:${eureka.port:8761}/eureka/
  instance:
    prefer-ip-address: true
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: refresh,bus-refresh,hystrix.stream
##        include: "*"
