spring:
  rabbitmq:
    host: 134.175.153.50
    port: 5672
    virtual-host: testhost
    username: admin
    password: admin
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: refresh,bus-refresh,hystrix.stream
##        include: "*"
